@baseUrl = http://localhost:8080

### Listar itens pendentes
GET {{baseUrl}}/cozinha/pendentes

### Listar itens em preparo
GET {{baseUrl}}/cozinha/em-preparo

### Iniciar preparo do item
PATCH {{baseUrl}}/cozinha/itens/1/iniciar-preparo

### Listar itens pendentes
GET {{baseUrl}}/cozinha/pendentes

### Marcar item como pronto
PATCH {{baseUrl}}/cozinha/itens/1/marcar-pronto

### Entregar item
PATCH {{baseUrl}}/cozinha/itens/1/entregar
